name: Build boost

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Node 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        go-version: '1.20'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Get dependencies
      run: go get -v ./...

    - name: Cache apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: build-essential bzr pkg-config clang curl gcc git hwloc jq libhwloc-dev wget mesa-opencl-icd ocl-icd-opencl-dev
        version: 1.0

    - name: Build boost
      run: make boost

    - name: LS dir
      run: |
        ls -lah .
        ls -lah boost
